name: Build & Test & Publish

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

jobs:

  build-on-macos:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build Tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:assemble -PonCICD

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:assemble -PonCICD

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Publish to MavenCentral
        run: ./publish_apple_android_jvm.sh

  build-on-windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build Tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:mingwX64MainKlibrary

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:mingwX64MainKlibrary

      - name: Publish to MavenCentral
        run: ./gradlew :sqllin-driver:publishMingwX64PublicationToMavenRepository && ./gradlew :sqllin-dsl:publishMingwX64PublicationToMavenRepository

  build-on-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build Tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}

      - name: Build sqllin-driver
        run: ./gradlew :sqllin-driver:assemble -PonCICD

      - name: Build sqllin-processor
        run: ./gradlew :sqllin-processor:assemble

      - name: Build sqllin-dsl
        run: ./gradlew :sqllin-dsl:assemble -PonCICD

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: Publish to MavenCentral
        run: ./publish_linux_processor.sh
